Code required to interact with Anti-Brownout in core 751
team751/2020Robot pull request #5
Opened 2020-01-20 22:20 UTC by Kevin-Woodman

The Anti-Brownout code (should) work with out this but just not adjustable.

2020-01-20 23:59 UTC, InsightGit requested changes
Looks good. I will handling merging(and switch this PR to approved) when the corresponding core751 PR gets approved.

2020-01-20 23:59 UTC, InsightGit commented on src/main/java/frc/robot/Robot.java
> +    SmartDashboard.putBoolean("Anit-Brownout mode", true);
i love me some anit-brownout mode

2020-01-20 23:59 UTC, InsightGit commented on src/main/java/frc/robot/Constants.java
> +    public static int driveStickPort = 0;
These are good for now with testing with 2019, but we will eventually need to change them to adapt to the new drivetrain with neos.

2020-01-22 01:53 UTC, dsaliba requested changes
Make it compile and ideally make this system a bit more robust, I would like to see a brownout handler we can construct that will allocate % of current to different components provide them with their modifiers accordingly, this may involve rebasing so you have more subsystems to work with. I can talk to you about this and i would also be willing to write at least a skeleton for it if you want. Other than that great work the drop in brownouts is very impressive.

2020-01-22 04:21 UTC, InsightGit commented
@dsaliba the reason it doesn't compile is because the upstream core751 PR #2 hasn't been merged yet.

2020-01-31 22:50 UTC, closed without merging